//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Projects\hackathonblazor_prosr_adminui\prosr.Parser\Parser\Prosr1.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class Prosr1Lexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, SYNTAX=13, PACKAGE=14, MESSAGE=15, HUB=16, 
		ACTION=17, CALLS=18, ON=19, REPEATED=20, TYPE=21, IDENT=22, NUMBER=23, 
		WHITESPACE=24;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "SYNTAX", "PACKAGE", "MESSAGE", "HUB", "ACTION", 
		"CALLS", "ON", "REPEATED", "TYPE", "IDENT", "NUMBER", "WHITESPACE"
	};


	public Prosr1Lexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public Prosr1Lexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "'prosr1'", "';'", "'{'", "'}'", "'('", "')'", "'caller'", 
		"'all'", "'''", "'\"'", "'.'", "'syntax'", "'package'", "'message'", "'hub'", 
		"'action'", "'calls'", "'on'", "'repeated'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "SYNTAX", "PACKAGE", "MESSAGE", "HUB", "ACTION", "CALLS", "ON", 
		"REPEATED", "TYPE", "IDENT", "NUMBER", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Prosr1.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static Prosr1Lexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1A', '\xAE', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x5', '\x16', '\x9B', '\n', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\x6', '\x17', '\x9F', '\n', '\x17', 
		'\r', '\x17', '\xE', '\x17', '\xA0', '\x3', '\x18', '\x6', '\x18', '\xA4', 
		'\n', '\x18', '\r', '\x18', '\xE', '\x18', '\xA5', '\x3', '\x19', '\x6', 
		'\x19', '\xA9', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\xAA', '\x3', 
		'\x19', '\x3', '\x19', '\x2', '\x2', '\x1A', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', 
		'\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', 
		'\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', 
		'\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', 
		'\x31', '\x1A', '\x3', '\x2', '\x6', '\x4', '\x2', '\x43', '\\', '\x63', 
		'|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', 
		'|', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\v', '\f', '\xF', '\xF', 
		'\"', '\"', '\x2', '\xB2', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x33', '\x3', '\x2', '\x2', '\x2', '\x5', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\a', '<', '\x3', '\x2', '\x2', '\x2', '\t', '>', '\x3', 
		'\x2', '\x2', '\x2', '\v', '@', '\x3', '\x2', '\x2', '\x2', '\r', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\xF', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x46', '\x3', '\x2', '\x2', '\x2', '\x13', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 'Q', '\x3', '\x2', '\x2', '\x2', '\x17', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x19', 'U', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'W', '\x3', '\x2', '\x2', '\x2', '\x1D', '^', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\x66', '\x3', '\x2', '\x2', '\x2', '!', 'n', '\x3', '\x2', '\x2', 
		'\x2', '#', 'r', '\x3', '\x2', '\x2', '\x2', '%', 'y', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\x7F', '\x3', '\x2', '\x2', '\x2', ')', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '+', '\x9A', '\x3', '\x2', '\x2', '\x2', '-', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '/', '\xA3', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\a', '?', '\x2', 
		'\x2', '\x34', '\x4', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 
		'r', '\x2', '\x2', '\x36', '\x37', '\a', 't', '\x2', '\x2', '\x37', '\x38', 
		'\a', 'q', '\x2', '\x2', '\x38', '\x39', '\a', 'u', '\x2', '\x2', '\x39', 
		':', '\a', 't', '\x2', '\x2', ':', ';', '\a', '\x33', '\x2', '\x2', ';', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '<', '=', '\a', '=', '\x2', '\x2', 
		'=', '\b', '\x3', '\x2', '\x2', '\x2', '>', '?', '\a', '}', '\x2', '\x2', 
		'?', '\n', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\a', '\x7F', '\x2', 
		'\x2', '\x41', '\f', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\a', 
		'*', '\x2', '\x2', '\x43', '\xE', '\x3', '\x2', '\x2', '\x2', '\x44', 
		'\x45', '\a', '+', '\x2', '\x2', '\x45', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '\x46', 'G', '\a', '\x65', '\x2', '\x2', 'G', 'H', '\a', '\x63', 
		'\x2', '\x2', 'H', 'I', '\a', 'n', '\x2', '\x2', 'I', 'J', '\a', 'n', 
		'\x2', '\x2', 'J', 'K', '\a', 'g', '\x2', '\x2', 'K', 'L', '\a', 't', 
		'\x2', '\x2', 'L', '\x12', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', 
		'\x63', '\x2', '\x2', 'N', 'O', '\a', 'n', '\x2', '\x2', 'O', 'P', '\a', 
		'n', '\x2', '\x2', 'P', '\x14', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', 
		'\a', ')', '\x2', '\x2', 'R', '\x16', '\x3', '\x2', '\x2', '\x2', 'S', 
		'T', '\a', '$', '\x2', '\x2', 'T', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'U', 'V', '\a', '\x30', '\x2', '\x2', 'V', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\a', 'u', '\x2', '\x2', 'X', 'Y', '\a', '{', '\x2', 
		'\x2', 'Y', 'Z', '\a', 'p', '\x2', '\x2', 'Z', '[', '\a', 'v', '\x2', 
		'\x2', '[', '\\', '\a', '\x63', '\x2', '\x2', '\\', ']', '\a', 'z', '\x2', 
		'\x2', ']', '\x1C', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', 'r', '\x2', 
		'\x2', '_', '`', '\a', '\x63', '\x2', '\x2', '`', '\x61', '\a', '\x65', 
		'\x2', '\x2', '\x61', '\x62', '\a', 'm', '\x2', '\x2', '\x62', '\x63', 
		'\a', '\x63', '\x2', '\x2', '\x63', '\x64', '\a', 'i', '\x2', '\x2', '\x64', 
		'\x65', '\a', 'g', '\x2', '\x2', '\x65', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\a', 'o', '\x2', '\x2', 'g', 'h', '\a', 'g', '\x2', 
		'\x2', 'h', 'i', '\a', 'u', '\x2', '\x2', 'i', 'j', '\a', 'u', '\x2', 
		'\x2', 'j', 'k', '\a', '\x63', '\x2', '\x2', 'k', 'l', '\a', 'i', '\x2', 
		'\x2', 'l', 'm', '\a', 'g', '\x2', '\x2', 'm', ' ', '\x3', '\x2', '\x2', 
		'\x2', 'n', 'o', '\a', 'j', '\x2', '\x2', 'o', 'p', '\a', 'w', '\x2', 
		'\x2', 'p', 'q', '\a', '\x64', '\x2', '\x2', 'q', '\"', '\x3', '\x2', 
		'\x2', '\x2', 'r', 's', '\a', '\x63', '\x2', '\x2', 's', 't', '\a', '\x65', 
		'\x2', '\x2', 't', 'u', '\a', 'v', '\x2', '\x2', 'u', 'v', '\a', 'k', 
		'\x2', '\x2', 'v', 'w', '\a', 'q', '\x2', '\x2', 'w', 'x', '\a', 'p', 
		'\x2', '\x2', 'x', '$', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '\x65', 
		'\x2', '\x2', 'z', '{', '\a', '\x63', '\x2', '\x2', '{', '|', '\a', 'n', 
		'\x2', '\x2', '|', '}', '\a', 'n', '\x2', '\x2', '}', '~', '\a', 'u', 
		'\x2', '\x2', '~', '&', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\a', 
		'q', '\x2', '\x2', '\x80', '\x81', '\a', 'p', '\x2', '\x2', '\x81', '(', 
		'\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\a', 't', '\x2', '\x2', '\x83', 
		'\x84', '\a', 'g', '\x2', '\x2', '\x84', '\x85', '\a', 'r', '\x2', '\x2', 
		'\x85', '\x86', '\a', 'g', '\x2', '\x2', '\x86', '\x87', '\a', '\x63', 
		'\x2', '\x2', '\x87', '\x88', '\a', 'v', '\x2', '\x2', '\x88', '\x89', 
		'\a', 'g', '\x2', '\x2', '\x89', '\x8A', '\a', '\x66', '\x2', '\x2', '\x8A', 
		'*', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', 'u', '\x2', '\x2', 
		'\x8C', '\x8D', '\a', 'v', '\x2', '\x2', '\x8D', '\x8E', '\a', 't', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', 'k', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'p', '\x2', '\x2', '\x90', '\x9B', '\a', 'i', '\x2', '\x2', '\x91', '\x92', 
		'\a', '\x64', '\x2', '\x2', '\x92', '\x93', '\a', 'q', '\x2', '\x2', '\x93', 
		'\x94', '\a', 'q', '\x2', '\x2', '\x94', '\x9B', '\a', 'n', '\x2', '\x2', 
		'\x95', '\x96', '\a', 'k', '\x2', '\x2', '\x96', '\x97', '\a', 'p', '\x2', 
		'\x2', '\x97', '\x98', '\a', 'v', '\x2', '\x2', '\x98', '\x99', '\a', 
		'\x35', '\x2', '\x2', '\x99', '\x9B', '\a', '\x34', '\x2', '\x2', '\x9A', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x95', '\x3', '\x2', '\x2', '\x2', '\x9B', ',', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9E', '\t', '\x2', '\x2', '\x2', '\x9D', 
		'\x9F', '\t', '\x3', '\x2', '\x2', '\x9E', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA4', '\t', '\x4', '\x2', '\x2', 
		'\xA3', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', 
		'\x2', '\x2', '\xA5', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '\xA6', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\xA7', '\xA9', '\t', '\x5', '\x2', '\x2', '\xA8', '\xA7', '\x3', '\x2', 
		'\x2', '\x2', '\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xA8', 
		'\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\x3', '\x2', '\x2', '\x2', 
		'\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\b', '\x19', 
		'\x2', '\x2', '\xAD', '\x32', '\x3', '\x2', '\x2', '\x2', '\b', '\x2', 
		'\x9A', '\x9E', '\xA0', '\xA5', '\xAA', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
