//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Projects\hackathonblazor_prosr_adminui\prosr.Parser\Parser\Prosr1.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IProsr1Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class Prosr1BaseListener : IProsr1Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContent([NotNull] Prosr1Parser.ContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContent([NotNull] Prosr1Parser.ContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.syntax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntax([NotNull] Prosr1Parser.SyntaxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.syntax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntax([NotNull] Prosr1Parser.SyntaxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinition([NotNull] Prosr1Parser.DefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinition([NotNull] Prosr1Parser.DefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.pkg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPkg([NotNull] Prosr1Parser.PkgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.pkg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPkg([NotNull] Prosr1Parser.PkgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.hub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHub([NotNull] Prosr1Parser.HubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.hub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHub([NotNull] Prosr1Parser.HubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.sending"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSending([NotNull] Prosr1Parser.SendingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.sending"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSending([NotNull] Prosr1Parser.SendingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.sendingMessageIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSendingMessageIdent([NotNull] Prosr1Parser.SendingMessageIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.sendingMessageIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSendingMessageIdent([NotNull] Prosr1Parser.SendingMessageIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.sendingTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSendingTarget([NotNull] Prosr1Parser.SendingTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.sendingTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSendingTarget([NotNull] Prosr1Parser.SendingTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.returning"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturning([NotNull] Prosr1Parser.ReturningContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.returning"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturning([NotNull] Prosr1Parser.ReturningContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.returningMessageIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturningMessageIdent([NotNull] Prosr1Parser.ReturningMessageIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.returningMessageIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturningMessageIdent([NotNull] Prosr1Parser.ReturningMessageIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.returningTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturningTarget([NotNull] Prosr1Parser.ReturningTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.returningTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturningTarget([NotNull] Prosr1Parser.ReturningTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessage([NotNull] Prosr1Parser.MessageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessage([NotNull] Prosr1Parser.MessageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] Prosr1Parser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] Prosr1Parser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.typeIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeIdent([NotNull] Prosr1Parser.TypeIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.typeIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeIdent([NotNull] Prosr1Parser.TypeIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuote([NotNull] Prosr1Parser.QuoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuote([NotNull] Prosr1Parser.QuoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.fieldIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldIdent([NotNull] Prosr1Parser.FieldIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.fieldIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldIdent([NotNull] Prosr1Parser.FieldIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.fullIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFullIdent([NotNull] Prosr1Parser.FullIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.fullIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFullIdent([NotNull] Prosr1Parser.FullIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.hubIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHubIdent([NotNull] Prosr1Parser.HubIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.hubIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHubIdent([NotNull] Prosr1Parser.HubIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.messageIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageIdent([NotNull] Prosr1Parser.MessageIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.messageIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageIdent([NotNull] Prosr1Parser.MessageIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.packageIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackageIdent([NotNull] Prosr1Parser.PackageIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.packageIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackageIdent([NotNull] Prosr1Parser.PackageIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.returningIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturningIdent([NotNull] Prosr1Parser.ReturningIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.returningIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturningIdent([NotNull] Prosr1Parser.ReturningIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.sendingIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSendingIdent([NotNull] Prosr1Parser.SendingIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.sendingIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSendingIdent([NotNull] Prosr1Parser.SendingIdentContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
