//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Projects\hackathonblazor_prosr_adminui\prosr.Parser\Parser\Prosr1.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Prosr1Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IProsr1Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContent([NotNull] Prosr1Parser.ContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContent([NotNull] Prosr1Parser.ContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.syntax"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSyntax([NotNull] Prosr1Parser.SyntaxContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.syntax"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSyntax([NotNull] Prosr1Parser.SyntaxContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] Prosr1Parser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] Prosr1Parser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.pkg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPkg([NotNull] Prosr1Parser.PkgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.pkg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPkg([NotNull] Prosr1Parser.PkgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.hub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHub([NotNull] Prosr1Parser.HubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.hub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHub([NotNull] Prosr1Parser.HubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.sending"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSending([NotNull] Prosr1Parser.SendingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.sending"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSending([NotNull] Prosr1Parser.SendingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.sendingMessageIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSendingMessageIdent([NotNull] Prosr1Parser.SendingMessageIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.sendingMessageIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSendingMessageIdent([NotNull] Prosr1Parser.SendingMessageIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.sendingTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSendingTarget([NotNull] Prosr1Parser.SendingTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.sendingTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSendingTarget([NotNull] Prosr1Parser.SendingTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.returning"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturning([NotNull] Prosr1Parser.ReturningContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.returning"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturning([NotNull] Prosr1Parser.ReturningContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.returningMessageIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturningMessageIdent([NotNull] Prosr1Parser.ReturningMessageIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.returningMessageIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturningMessageIdent([NotNull] Prosr1Parser.ReturningMessageIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.returningTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturningTarget([NotNull] Prosr1Parser.ReturningTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.returningTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturningTarget([NotNull] Prosr1Parser.ReturningTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessage([NotNull] Prosr1Parser.MessageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessage([NotNull] Prosr1Parser.MessageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] Prosr1Parser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] Prosr1Parser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.typeIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeIdent([NotNull] Prosr1Parser.TypeIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.typeIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeIdent([NotNull] Prosr1Parser.TypeIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuote([NotNull] Prosr1Parser.QuoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuote([NotNull] Prosr1Parser.QuoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.fieldIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldIdent([NotNull] Prosr1Parser.FieldIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.fieldIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldIdent([NotNull] Prosr1Parser.FieldIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.fullIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFullIdent([NotNull] Prosr1Parser.FullIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.fullIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFullIdent([NotNull] Prosr1Parser.FullIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.hubIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHubIdent([NotNull] Prosr1Parser.HubIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.hubIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHubIdent([NotNull] Prosr1Parser.HubIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.messageIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageIdent([NotNull] Prosr1Parser.MessageIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.messageIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageIdent([NotNull] Prosr1Parser.MessageIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.packageIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackageIdent([NotNull] Prosr1Parser.PackageIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.packageIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackageIdent([NotNull] Prosr1Parser.PackageIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.returningIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturningIdent([NotNull] Prosr1Parser.ReturningIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.returningIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturningIdent([NotNull] Prosr1Parser.ReturningIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Prosr1Parser.sendingIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSendingIdent([NotNull] Prosr1Parser.SendingIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Prosr1Parser.sendingIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSendingIdent([NotNull] Prosr1Parser.SendingIdentContext context);
}
